"""add document metadata

Revision ID: dc656f5afcfd
Revises: fd2396bf92f6
Create Date: 2026-07-22 11:15:30.900752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc656f5afcfd'
down_revision: Union[str, Sequence[str], None] = 'fd2396bf92f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('stored_filename', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('file_path', sa.String(length=500), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.BigInteger(), nullable=False))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'documents', ['stored_filename'])
    op.drop_column('documents', 'filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'stored_filename')
    op.drop_column('documents', 'original_filename')
    # ### end Alembic commands ###
